[sqlalchemy]
database_url = postgresql://postgres:nexr1234@database:5432/quetz

[session]
# openssl rand -hex 32
secret = "b72376b88e6f249cb0921052ea8a092381ca17fd8bb0caf4d847e337b3d34cf8"
https_only = false

[logging]
level = "DEBUG"
file = "quetz.log"

[pamauthenticator]
provider = "pam"
admin_groups = ["quetz", "nexr"]
maintainer_groups = ["nexr"]
user_groups = ["nexr"]

[local_store]
redirect_enabled = true
